dependencies:
- python=3.6
- pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - keras
    - pytorch
    - tensorflow
    - torchvision
    - xgboost
    - pandas-datareader 
    - plotly 
    - Scrapy 
    - django 
    - pymysql 
    - seaborn 
    - scikit-learn
